--liquibase formatted sql

--changeset jokerSharp:1

CREATE TABLE IF NOT EXISTS public.order
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT NOT NULL REFERENCES public.customer(id),
    email VARCHAR(256),
    status INTEGER NOT NULL,
    CONSTRAINT order_pkey PRIMARY KEY (id)
);

ALTER TABLE public.customer
ADD COLUMN order_id BIGINT REFERENCES public.order(id);

CREATE TABLE IF NOT EXISTS public.order_product
(
    order_id BIGINT NOT NULL REFERENCES public.order(id),
    product_id UUID NOT NULL REFERENCES public.product(id),
    CONSTRAINT order_product_pkey PRIMARY KEY (order_id, product_id)
);