--liquibase formatted sql

--changeset jokerSharp:1

CREATE TABLE IF NOT EXISTS public.customer
(
id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(128) NOT NULL,
email VARCHAR(256),
CONSTRAINT customer_pkey PRIMARY KEY (id)
);